### ISSUE TITLE
插座状态获取接口失效

### ISSUE THREAD

**Issue by tinywisdom** [EricZhu-42/ChargingStationMonitor#6]
疑似是公众号经过了升级，插座状态获取接口失效了，现在点击正在使用中的插座后，会出现是否订阅插座的弹窗，影响到了南哪充电的信息更新

![QQ截图20240425154244](https://github.com/EricZhu-42/ChargingStationMonitor/assets/74707326/4ec4c9b1-541d-4bb0-af46-9a7b5ca30256)

**Comment by EricZhu-42** [comment]
感谢反馈，原先获取插座状态的 API 目前似乎已经无法正常使用。我们考虑换用另一个获取充电站状态的 API 以实现类似的功能，但这个 API 需要带用户登录凭据访问，封号风险与失效风险都会大一些。

**目前网站的信息更新将暂时停止**，这两天我看看是否有其他方法能够恢复。

**Comment by EricZhu-42** [comment]
> 感谢反馈，原先获取插座状态的 API 目前似乎已经无法正常使用。我们考虑换用另一个获取充电站状态的 API 以实现类似的功能，但这个 API 需要带用户登录凭据访问，封号风险与失效风险都会大一些。
> 
> **目前网站的信息更新将暂时停止**，这两天我看看是否有其他方法能够恢复。

更新：现在原 API 也需要带登录凭据才能访问。

为了减小请求数，我们换用了获取充电站整体状态的 API 实现了原先的功能，但可能导致 ”已占用时间“ 等数据存在误差。

**目前数据更新已恢复**，可以观察一段时间看看运行是否稳定。

**Comment by tinywisdom** [comment]
感谢感谢！辛苦辛苦~
