### ISSUE TITLE
新功能请求

### ISSUE THREAD

**Issue by Do1e** [EricZhu-42/ChargingStationMonitor#7]
是否考虑将占用时间改为剩余时间呢？

**Comment by EricZhu-42** [comment]
Hi，感谢建议！

理论上我们可以拿到剩余的**最大充电时间** —— 例如，用户支付 2￥，最大充电 10 小时，现已充电 2 小时，因此剩余时间为 8 小时。

但是，考虑到绝大部分车不需要 10 小时即可充满，实际决定车辆占用充电桩时间的因素应当是这辆车**还需要充多久才能充满** —— 而该数据取决于车型及初始电量，无法通过充电桩获得，只能等车辆断电后改变状态。

如果有其他同学有更好的想法，欢迎加入讨论~

**Comment by Do1e** [comment]
我看API的返回是有`restmin`和`usedmin`参数的，如果不改的话可以考虑加上这一项会更直观一些。
